package qrohan.eden.core.tools.factory;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import qrohan.eden.core.misc.JsonUtils;
import qrohan.eden.core.stream.AbstractObject;
import qrohan.eden.core.misc.BuildInfo;

import freemarker.template.Configuration;
import freemarker.template.Template;
import freemarker.template.TemplateException;
import freemarker.template.TemplateExceptionHandler;
import org.json.JSONObject;

/**
 * Class for factory object
 */
public class Factory extends AbstractObject {
	// --- BEGIN FIELDS ---

	/**
	 * Generation directory
	 * <p>The classes generated by the factory are store in this directory</p>
	 */
	private String generationDir;

	// --- END FIELDS ---

	// --- BEGIN CONSTRUCTORS/DESTRUCTORS ---

	/**
	 * Default constructor
	 */
	public Factory()
	{
		super();
		reset();
	}

	// --- END CONSTRUCTORS/DESTRUCTORS ---

	// --- BEGIN PUBLIC METHODS

	/**
	 * Reset factory
	 * <p>The generation directory is reset to the HOME directory</p>>
	 */
	public void reset()
	{
		this.generationDir = System.getProperty("user.home");
	}

	/**
	 * Get generation directory
	 * @return generation directory
	 */
	public String getGenerationDir()
	{
		return this.generationDir;
	}

	/**
	 * Set generation directory
	 * @param path new generation directory
	 */
	public void setGenerationDir(String path)
	{
		this.generationDir = path;
	}

	/**
	 * Generate the class from a JSON file
	 * @param file file name or path of the JSON file
	 * @param outputPackage package of the generated class
	 * @throws IOException If the generation fails
	 */
	public void createFromJson(String file, String outputPackage) throws IOException
	{
		// create generation context
		JSONObject context = JsonUtils.createJsonObject(file);
		context.put("user", BuildInfo.getUser());
		context.put("date", BuildInfo.getDate());
		context.put("version", BuildInfo.getVersion());
		context.put("module", BuildInfo.getModule());
		context.put("package", (outputPackage == null || outputPackage.isBlank()) ? context.get("name") : outputPackage);

		// create generation directory
		try {
			Path p = Paths.get(this.generationDir);
			Files.createDirectories(p);
		} catch (IOException e) {
			error(e.getMessage());
			return;
		}

		// generate
		generate(context);
	}

	// --- END PUBLIC METHODS ---

	// --- BEGIN PRIVATE METHODS

	/**
	 * Generate a class
	 * @param context input json object
	 * @throws IOException If the generation fails
	 */
	private void generate(JSONObject context) throws IOException
	{
		// create template configuration
		Configuration cfg = new Configuration(Configuration.VERSION_2_3_33);
		cfg.setClassForTemplateLoading(this.getClass(), "/templates/");
		cfg.setDefaultEncoding("UTF-8");
		cfg.setTemplateExceptionHandler(TemplateExceptionHandler.RETHROW_HANDLER);

		// render template
		String name = context.get("name").toString();
		String className = name.substring(0, 1).toUpperCase() + name.substring(1);
		Template template = cfg.getTemplate("TemplateClass.java.ftl");
		File mainFile = Paths.get(this.generationDir, className + ".java").toFile();
		if (!mainFile.createNewFile()) {
			warning(mainFile.getAbsolutePath() + " already exists");
		}
        try (Writer fileWriter = new FileWriter(mainFile)) {
            template.process(context.toMap(), fileWriter);
        } catch (TemplateException e) {
            error(e.getMessage());
			return;
        }

		// done :)
		info("Successfully generate " + mainFile.getName() + " in directory " + getGenerationDir());
	}

	// --- END PRIVATE METHODS ---
} // END OF CLASS
